### PR TITLE
add generated parser.c's 

### PR DESCRIPTION
**Pull request by unhammer**
https://github.com/tree-sitter/tree-sitter-* repos do this, and emacs 29+ expects .c files to exist (see new function `treesit-install-language-grammar`)

### CODE REVIEW

**Comment by TinoDidriksen** [comment]
https://github.com/apertium/tree-sitter-apertium/commit/298f1fa46a42a8bd9ae09e3e6a74437f4106521b explicitly omitted precompiled files. See also https://tinodidriksen.com/pisg/OFTC/logs/%23apertium/2022-07-06.log and https://github.com/tree-sitter/tree-sitter/issues/730

**Comment by unhammer** [comment]
https://github.com/tree-sitter/tree-sitter/issues/730 is still open though, meaning consumers expect to find generated files in source (cf https://github.com/emacs-mirror/emacs/blob/4e4a808eca8f68a8079272442aab0f8815abdaa8/lisp/treesit.el#L2696 ). From what I can tell, https://github.com/tree-sitter doesn't yet provide an alternative guidance for how to serve the generated files; I would prefer we follow them (ie do what they do now and switch when they switch).

**Comment by TinoDidriksen** [comment]
Yeah, I came to the same conclusion. It sucks, but at least it sucks equally for everyone.

**Comment by mr-martian** [comment]
It seems to me that this situation is annoying in either direction - I'm fine with either choice.

**Comment by mr-martian** [comment]
OTOH, https://github.com/tree-sitter/tree-sitter/issues/730 mentions the possibility of marking generated files as binary in `.gitattributes`, which at least makes diffs less annoying to read, so perhaps we could add that and then merge this PR?

**Pull request closed without merging**
